In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from pathlib import Path

cur_path = Path('.').resolve()
cur_path

WindowsPath('C:/Users/chlje/VSCodeProjects/FinanceDashboard/pricevolume')

dr = pd.date_range(start='20210101', end='20211231')
dr

In [4]:
import pandas as pd

kosdaq_df = pd.read_pickle(cur_path / "cache" / "KSQ_20150101_to_20211031_lv1_df.pkl")
kospi_df = pd.read_pickle(cur_path / "cache" / "STK_20150101_to_20211031_lv1_df.pkl")

In [13]:
kospi_df.iloc[8000]

ISU_SRT_CD             001755
ISU_ABBRV               한양증권우
MKT_NM                  KOSPI
SECT_TP_NM                   
TDD_CLSPRC             6600.0
FLUC_TP_CD                2.0
CMPPREVDD_PRC           -90.0
FLUC_RT                 -1.35
TDD_OPNPRC             6500.0
TDD_HGPRC              6600.0
TDD_LWPRC              6500.0
ACC_TRDVOL               21.0
ACC_TRDVAL           136600.0
MKTCAP           3465000000.0
LIST_SHRS            525000.0
MKT_ID                    STK
trdDd                20150109
Name: 8000, dtype: object

In [14]:
kospi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2244861 entries, 0 to 2244860
Data columns (total 17 columns):
 #   Column         Dtype  
---  ------         -----  
 0   ISU_SRT_CD     object 
 1   ISU_ABBRV      object 
 2   MKT_NM         object 
 3   SECT_TP_NM     object 
 4   TDD_CLSPRC     float64
 5   FLUC_TP_CD     float64
 6   CMPPREVDD_PRC  float64
 7   FLUC_RT        float64
 8   TDD_OPNPRC     float64
 9   TDD_HGPRC      float64
 10  TDD_LWPRC      float64
 11  ACC_TRDVOL     float64
 12  ACC_TRDVAL     float64
 13  MKTCAP         float64
 14  LIST_SHRS      float64
 15  MKT_ID         object 
 16  trdDd          int64  
dtypes: float64(11), int64(1), object(5)
memory usage: 291.2+ MB


In [10]:
kospi_df.iloc[:, 4:15] = kospi_df.iloc[:, 4:15].replace(regex=",", value="")

In [11]:
# kospi_df['MKTCAP'] = kospi_df['MKTCAP'].replace("-", np.nan)
kospi_df.iloc[:, 4:15] = kospi_df.iloc[:, 4:15].replace("-", value=np.nan)

In [12]:
# kospi_df['MKTCAP'] = kospi_df['MKTCAP'].astype('float')
kospi_df.iloc[:, 4:15] = kospi_df.iloc[:, 4:15].astype('float')

## lv2 conversion

### method 1: dataframe pivot

In [52]:
lv2_df = kospi_df.pivot(index="trdDd", columns="ISU_SRT_CD", values="MKTCAP")
lv2_df

ISU_SRT_CD        000020        000030        000040        000050  \
trdDd                                                                
20150101             NaN           NaN           NaN           NaN   
20150102    1.544610e+11  6.620765e+12  1.247117e+11  5.140363e+11   
20150103             NaN           NaN           NaN           NaN   
20150104             NaN           NaN           NaN           NaN   
20150105    1.536231e+11  6.512561e+12  1.259052e+11  5.085533e+11   
...                  ...           ...           ...           ...   
20211027    4.580761e+11           NaN  9.709874e+10  3.646231e+11   
20211028    4.734384e+11           NaN  9.950218e+10  3.605108e+11   
20211029    4.566795e+11           NaN  9.950218e+10  3.646231e+11   
20211030             NaN           NaN           NaN           NaN   
20211031             NaN           NaN           NaN           NaN   

ISU_SRT_CD        000060        000070        000075        000080  \
trdDd                                                                
20150101             NaN           NaN           NaN           NaN   
20150102    1.335134e+12  7.690715e+11  1.245118e+10  1.585020e+12   
20150103             NaN           NaN           NaN           NaN   
20150104             NaN           NaN           NaN           NaN   
20150105    1.313941e+12  7.596508e+11  1.229915e+10  1.616580e+12   
...                  ...           ...           ...           ...   
20211027    3.558438e+12  9.249413e+11  2.143609e+10  2.507277e+12   
20211028    3.510188e+12  8.949663e+11  2.122325e+10  2.475716e+12   
20211029    3.341312e+12  8.821199e+11  2.094960e+10  2.440650e+12   
20211030             NaN           NaN           NaN           NaN   
20211031             NaN           NaN           NaN           NaN   

ISU_SRT_CD        000087        000100  ...        381970        383220  \
trdDd                                   ...                               
20150101             NaN           NaN  ...           NaN           NaN   
20150102    2.034248e+10  1.884780e+12  ...           NaN           NaN   
20150103             NaN           NaN  ...           NaN           NaN   
20150104             NaN           NaN  ...           NaN           NaN   
20150105    1.989043e+10  1.873628e+12  ...           NaN           NaN   
...                  ...           ...  ...           ...           ...   
20211027    2.378940e+10  4.310334e+12  ...  1.197355e+12  6.596478e+12   
20211028    2.356338e+10  4.254356e+12  ...  1.204568e+12  6.688415e+12   
20211029    2.361988e+10  4.191380e+12  ...  1.178120e+12  6.650108e+12   
20211030             NaN           NaN  ...           NaN           NaN   
20211031             NaN           NaN  ...           NaN           NaN   

ISU_SRT_CD        383800        38380K        395400        900050  \
trdDd                                                                
20150101             NaN           NaN           NaN           NaN   
20150102             NaN           NaN           NaN  4.123225e+11   
20150103             NaN           NaN           NaN           NaN   
20150104             NaN           NaN           NaN           NaN   
20150105             NaN           NaN           NaN  3.877993e+11   
...                  ...           ...           ...           ...   
20211027    6.933915e+11  2.051399e+10  1.002983e+12           NaN   
20211028    6.819494e+11  2.036746e+10  9.921314e+11           NaN   
20211029    6.727957e+11  2.022093e+10  9.936816e+11           NaN   
20211030             NaN           NaN           NaN           NaN   
20211031             NaN           NaN           NaN           NaN   

ISU_SRT_CD        900140        950010        950100        950210  
trdDd                                                               
20150101             NaN           NaN           NaN           NaN  
20150102    9.071272e+11  3.314413e+09  4.273380e+11           NaN  
20150103       

### method 2: numpy iteration

In [25]:
date_list = kospi_df.loc[:, "trdDd"].unique()
sid_list = kospi_df.loc[:, "ISU_SRT_CD"].unique()

lv2_arr = np.empty((len(date_list), len(sid_list)))
lv2_arr[:] = np.nan

In [42]:
date_list_mapper = dict(zip(date_list, range(len(date_list))))
sid_list_mapper = dict(zip(sid_list, range(len(sid_list))))

In [43]:
mktcap_df = kospi_df.loc[:, ["trdDd", "ISU_SRT_CD", "MKTCAP"]].copy()

In [44]:
mktcap_arr = np.array(mktcap_df)

In [50]:
for row in mktcap_arr:
    date_idx = date_list_mapper[row[0]]
    sid_idx = sid_list_mapper[row[1]]
    value = row[2]

    lv2_arr[date_idx, sid_idx] = value

### method 3: numpy broadcasting

In [87]:
date_list = kospi_df.loc[:, "trdDd"].unique()
sid_list = kospi_df.loc[:, "ISU_SRT_CD"].unique()

lv2_arr = np.empty((len(date_list), len(sid_list)))
lv2_arr[:] = np.nan

In [54]:
date_list_mapper = dict(zip(date_list, range(len(date_list))))
sid_list_mapper = dict(zip(sid_list, range(len(sid_list))))

In [94]:
date_list_arr = np.array(list(map(lambda x: date_list_mapper[x], kospi_df["trdDd"]))) # row
date_list_arr = date_list_arr[:, None]

sid_list_arr = np.array(list(map(lambda x: sid_list_mapper[x], kospi_df["ISU_SRT_CD"]))) # column
sid_list_arr = sid_list_arr[None, :]

In [95]:
len(date_list_arr)

2244861

In [96]:
len(sid_list_arr[0])

2244861

In [97]:
lv2_arr.shape

(2496, 1045)

In [98]:
value_list_arr = np.array(kospi_df.loc[:, "MKTCAP"])

In [99]:
len(value_list_arr)

2244861

In [ ]:
2496 * 1045

In [101]:
lv2_arr[date_list_arr, sid_list_arr] = value_list_arr

In [58]:
arr = np.array([
    [1, 2, 3],
    [1, 2, 3]
])

In [68]:
arr[None, :]

array([[[1, 2, 3],
        [1, 2, 3]]])

In [69]:
arr[:, None]

array([[[1, 2, 3]],

       [[1, 2, 3]]])

In [70]:
A = np.zeros(16).reshape(4, 4)
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
r = np.array([1, 3])
c = np.array([0, 2])

In [75]:
r[:, None]

array([[1],
       [3]])

In [74]:
c[None, :]

array([[0, 2]])

In [77]:
A[r, c] = np.array([3, 4])
A

array([[0., 0., 0., 0.],
       [3., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 4., 0.]])

In [74]:
trdDd_df = kospi_df.groupby(by='trdDd')['MKTCAP'].sum(min_count=1).isnull()
trdDd_df

trdDd
20150101     True
20150102    False
20150103     True
20150104     True
20150105    False
            ...  
20211027    False
20211028    False
20211029    False
20211030     True
20211031     True
Name: MKTCAP, Length: 2496, dtype: bool

In [76]:
trdDd_df.index

Int64Index([20150101, 20150102, 20150103, 20150104, 20150105, 20150106,
            20150107, 20150108, 20150109, 20150110,
            ...
            20211022, 20211023, 20211024, 20211025, 20211026, 20211027,
            20211028, 20211029, 20211030, 20211031],
           dtype='int64', name='trdDd', length=2496)

In [ ]:
ss = kospi_df.reindex(index=trdDd_df.index, columns=kospi_df["ISU_SRT_CD"].unique(),) # lv2를 load할 때 필요. 
ss

In [100]:
ss.loc[20150101, '068400'] = 1

In [106]:
# TODO: Use numba

np.array(kospi_df)[7000]


array(['005740', '크라운제과', 'KOSPI', '', '206,000', '1', '1,000', '0.49',
       '205,000', '208,000', '199,000', '12,798', '2,602,134,500',
       303545944000.0, '1,473,524', 'STK', 20150108], dtype=object)